# Generated by Django 4.1 on 2022-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description1', models.TextField(max_length=150, verbose_name='description')),
                ('description2', models.TextField(max_length=150, verbose_name='description')),
                ('description3', models.TextField(max_length=150, verbose_name='description')),
                ('image', models.ImageField(upload_to='About/')),
            ],
            options={
                'verbose_name_plural': '2 - About',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Portfolio/')),
            ],
            options={
                'verbose_name_plural': '4 - Exhibitions',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Portfolio/')),
            ],
            options={
                'verbose_name_plural': '3 - Gallery',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='Home/')),
            ],
            options={
                'verbose_name_plural': '1 - Home',
            },
        ),
    ]
