# Generated by Django 4.1 on 2022-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': '5 - Social_Profile',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='description1',
            field=models.TextField(max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description2',
            field=models.TextField(max_length=350, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description3',
            field=models.TextField(max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
